;;;; -*- lisp -*-
;;;;============================================================================
;;;; MPICH2 bindings for SBCL
;;;; Copyright (c) 2011 Valentin Pavlov <x.pavlov@gmail.com>
;;;;
;;;; Permission is hereby granted, free of charge, to any person
;;;; obtaining a copy of this software and associated documentation
;;;; files (the "Software"), to deal in the Software without
;;;; restriction, including without limitation the rights to use,
;;;; copy, modify, merge, publish, distribute, sublicense, and/or sell
;;;; copies of the Software, and to permit persons to whom the
;;;; Software is furnished to do so, subject to the following
;;;; conditions:
;;;; 
;;;; The above copyright notice and this permission notice shall be
;;;; included in all copies or substantial portions of the Software.
;;;; 
;;;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;;;; EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
;;;; OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
;;;; NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
;;;; HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
;;;; WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
;;;; FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
;;;; OTHER DEALINGS IN THE SOFTWARE.
;;;;----------------------------------------------------------------------------
;;;; The SB-MPICH2 package definition
;;;;============================================================================
(defpackage #:sb-mpich2
  (:use #:cl #:sb-alien)
  (:export

   ;; from early-mpi
   #:MPI_SUCCESS
   #:MPI_THREAD_MULTIPLE
   #:MPI_COMM_WORLD
   #:*mpi-world-rank*
   #:MPI_Comm
   #:MPI_Init
   #:MPI_Init_thread
   #:MPI_Comm_rank
   #:MPI_Initialized
   #:with-mpi-call

   ;; from mpi-h
   #:MPI_IDENT
   #:MPI_CONGRUENT
   #:MPI_SIMILAR
   #:MPI_UNEQUAL
   #:MPI_Datatype
   #:MPI_CHAR
   #:MPI_SIGNED_CHAR
   #:MPI_UNSIGNED_CHAR
   #:MPI_BYTE
   #:MPI_WCHA
   #:MPI_SHORT
   #:MPI_UNSIGNED_SHORT
   #:MPI_INT
   #:MPI_UNSIGNED
   #:MPI_LONG
   #:MPI_UNSIGNED_LONG
   #:MPI_FLOAT
   #:MPI_DOUBLE
   #:MPI_LONG_DOUBLE
   #:MPI_LONG_LONG_INT
   #:MPI_UNSIGNED_LONG_LONG
   #:MPI_LONG_LONG
   #:MPI_PACKED
   #:MPI_LB
   #:MPI_UB
   #:MPI_FLOAT_INT
   #:MPI_DOUBLE_INT
   #:MPI_LONG_INT
   #:MPI_SHORT_INT
   #:MPI_2INT
   #:MPI_LONG_DOUBLE_INT
   #:MPI_COMPLEX
   #:MPI_DOUBLE_COMPLEX
   #:MPI_LOGICAL
   #:MPI_REAL
   #:MPI_DOUBLE_PRECISION
   #:MPI_INTEGER
   #:MPI_2INTEGER
   #:MPI_2COMPLEX
   #:MPI_2DOUBLE_COMPLEX
   #:MPI_2REAL
   #:MPI_2DOUBLE_PRECISION
   #:MPI_CHARACTER
   #:MPI_REAL4
   #:MPI_REAL8
   #:MPI_REAL16
   #:MPI_COMPLEX8
   #:MPI_COMPLEX16
   #:MPI_COMPLEX32
   #:MPI_INTEGER1
   #:MPI_INTEGER2
   #:MPI_INTEGER4
   #:MPI_INTEGER8
   #:MPI_DATATYPE_NULL
   #:MPI_INTEGER16
   #:MPI_TYPECLASS_REAL
   #:MPI_TYPECLASS_INTEGER
   #:MPI_TYPECLASS_COMPLEX
   #:MPI_COMM_SELF
   #:MPI_Group
   #:MPI_GROUP_EMPTY
   #:MPI_Win
   #:MPI_WIN_NULL
   #:MPI_File
   #:MPI_FILE_NULL
   #:MPI_Op
   #:MPI_MAX
   #:MPI_MIN
   #:MPI_SUM
   #:MPI_PROD
   #:MPI_LAND
   #:MPI_BAND
   #:MPI_LOR
   #:MPI_BOR
   #:MPI_LXOR
   #:MPI_BXOR
   #:MPI_MINLOC
   #:MPI_MAXLOC
   #:MPI_REPLACE
   #:MPI_TAG_UB
   #:MPI_HOST
   #:MPI_IO
   #:MPI_WTIME_IS_GLOBAL
   #:MPI_UNIVERSE_SIZE
   #:MPI_LASTUSEDCODE
   #:MPI_APPNUM
   #:MPI_WIN_BASE
   #:MPI_WIN_SIZE
   #:MPI_WIN_DISP_UNIT
   #:MPI_COMM_NULL
   #:MPI_OP_NULL
   #:MPI_GROUP_NULL
   #:MPI_REQUEST_NULL
   #:MPI_ERRHANDLER_NULL
   #:MPI_MAX_PROCESSOR_NAME
   #:MPI_MAX_ERROR_STRING
   #:MPI_MAX_PORT_NAME
   #:MPI_MAX_OBJECT_NAME
   #:MPI_UNDEFINED
   #:MPI_UNDEFINED_RANK
   #:MPI_KEYVAL_INVALID
   #:MPI_BSEND_OVERHEAD
   #:MPIR_Topo_type
   #:MPI_GRAPH
   #:MPI_CART
   #:MPI_BOTTOM
   #:MPI_PROC_NULL
   #:MPI_ANY_SOURCE
   #:MPI_ROOT
   #:MPI_ANY_TAG
   #:MPI_LOCK_EXCLUSIVE
   #:MPI_LOCK_SHARED
   #:MPI_Handler_function
   #:MPI_Comm_copy_attr_function
   #:MPI_Comm_delete_attr_function
   #:MPI_Type_copy_attr_function
   #:MPI_Type_delete_attr_function
   #:MPI_Win_copy_attr_function
   #:MPI_Win_delete_attr_function
   #:MPI_Comm_errhandler_fn
   #:MPI_File_errhandler_fn
   #:MPI_Win_errhandler_fn
   #:MPI_ERRORS_ARE_FATAL
   #:MPI_ERRORS_RETURN
   #:MPIR_ERRORS_THROW_EXCEPTIONS
   #:MPI_Errhandler
   #:MPIR_Dup_fn
   #:MPI_NULL_COPY_FN
   #:MPI_NULL_DELETE_FN
   #:MPI_COMM_NULL_COPY_FN
   #:MPI_COMM_NULL_DELETE_FN
   #:MPI_COMM_DUP_FN
   #:MPI_WIN_NULL_COPY_FN
   #:MPI_WIN_NULL_DELETE_FN
   #:MPI_WIN_DUP_FN
   #:MPI_TYPE_NULL_COPY_FN
   #:MPI_TYPE_NULL_DELETE_FN
   #:MPI_TYPE_DUP_FN
   #:MPI_Request
   #:MPI_User_function
   #:MPI_Copy_function
   #:MPI_Delete_function
   #:MPI_VERSION
   #:MPI_SUBVERSION
   #:MPICH_NAME
   #:MPICH2
   #:MPICH_HAS_C2F
   #:MPICH2_VERSION
   #:MPICH2_NUMVERSION
   #:MPICH2_RELEASE_TYPE_ALPHA
   #:MPICH2_RELEASE_TYPE_BETA
   #:MPICH2_RELEASE_TYPE_RC
   #:MPICH2_RELEASE_TYPE_PATCH
   #:MPICH2_CALC_VERSION
   #:MPI_COMBINER_ENUM
   #:MPI_COMBINER_NAMED
   #:MPI_COMBINER_DUP
   #:MPI_COMBINER_CONTIGUOUS
   #:MPI_COMBINER_VECTOR
   #:MPI_COMBINER_HVECTOR_INTEGER
   #:MPI_COMBINER_HVECTOR
   #:MPI_COMBINER_INDEXED
   #:MPI_COMBINER_HINDEXED_INTEGER
   #:MPI_COMBINER_HINDEXED
   #:MPI_COMBINER_INDEXED_BLOCK
   #:MPI_COMBINER_STRUCT_INTEGER
   #:MPI_COMBINER_STRUCT
   #:MPI_COMBINER_SUBARRAY
   #:MPI_COMBINER_DARRAY
   #:MPI_COMBINER_F90_REAL
   #:MPI_COMBINER_F90_COMPLEX
   #:MPI_COMBINER_F90_INTEGER
   #:MPI_COMBINER_RESIZED
   #:MPI_Info
   #:MPI_INFO_NULL
   #:MPI_MAX_INFO_KEY
   #:MPI_MAX_INFO_VAL
   #:MPI_ORDER_C
   #:MPI_ORDER_FORTRAN
   #:MPI_DISTRIBUTE_BLOCK
   #:MPI_DISTRIBUTE_CYCLIC
   #:MPI_DISTRIBUTE_NONE
   #:MPI_DISTRIBUTE_DFLT_DARG
   #:MPI_IN_PLACE
   #:MPI_MODE_NOCHECK
   #:MPI_MODE_NOSTORE
   #:MPI_MODE_NOPUT
   #:MPI_MODE_NOPRECEDE
   #:MPI_MODE_NOSUCCEED
   #:MPI_Aint
   #:MPI_Fint
   #:MPI_Offset
   #:MPI_Status
   #:MPI_Comm_c2f
   #:MPI_Comm_f2c
   #:MPI_Type_c2f
   #:MPI_Type_f2c
   #:MPI_Group_c2f
   #:MPI_Group_f2c
   #:MPI_Info_c2f
   #:MPI_Info_f2c
   #:MPI_Request_c2f
   #:MPI_Request_f2c
   #:MPI_Op_c2f
   #:MPI_Op_f2c
   #:MPI_Errhandler_c2f
   #:MPI_Errhandler_f2c
   #:MPI_Win_c2f
   #:MPI_Win_f2c
   #:PMPI_Comm_c2f
   #:PMPI_Comm_f2c
   #:PMPI_Type_c2f
   #:PMPI_Type_f2c
   #:PMPI_Group_c2f
   #:PMPI_Group_f2c
   #:PMPI_Info_c2f
   #:PMPI_Info_f2c
   #:PMPI_Request_c2f
   #:PMPI_Request_f2c
   #:PMPI_Op_c2f
   #:PMPI_Op_f2c
   #:PMPI_Errhandler_c2f
   #:PMPI_Errhandler_f2c
   #:PMPI_Win_c2f
   #:PMPI_Win_f2c
   #:MPI_STATUS_IGNORE
   #:MPI_STATUSES_IGNORE
   #:MPI_ERRCODES_IGNORE
   #:MPI_ARGV_NULL
   #:MPI_ARGVS_NULL
   #:MPI_THREAD_SINGLE
   #:MPI_THREAD_FUNNELED
   #:MPI_THREAD_SERIALIZED
   #:MPI_Grequest_cancel_function
   #:MPI_Grequest_free_function
   #:MPI_Grequest_query_function
   #:MPI_ERR_BUFFER
   #:MPI_ERR_COUNT
   #:MPI_ERR_TYPE
   #:MPI_ERR_TAG
   #:MPI_ERR_COMM
   #:MPI_ERR_RANK
   #:MPI_ERR_ROOT
   #:MPI_ERR_TRUNCATE
   #:MPI_ERR_GROUP
   #:MPI_ERR_OP
   #:MPI_ERR_REQUEST
   #:MPI_ERR_TOPOLOGY
   #:MPI_ERR_DIMS
   #:MPI_ERR_ARG
   #:MPI_ERR_OTHER
   #:MPI_ERR_UNKNOWN
   #:MPI_ERR_INTERN
   #:MPI_ERR_IN_STATUS
   #:MPI_ERR_PENDING
   #:MPI_ERR_FILE
   #:MPI_ERR_ACCESS
   #:MPI_ERR_AMODE
   #:MPI_ERR_BAD_FILE
   #:MPI_ERR_FILE_EXISTS
   #:MPI_ERR_FILE_IN_USE
   #:MPI_ERR_NO_SPACE
   #:MPI_ERR_NO_SUCH_FILE
   #:MPI_ERR_IO
   #:MPI_ERR_READ_ONLY
   #:MPI_ERR_CONVERSION
   #:MPI_ERR_DUP_DATAREP
   #:MPI_ERR_UNSUPPORTED_DATAREP
   #:MPI_ERR_INFO
   #:MPI_ERR_INFO_KEY
   #:MPI_ERR_INFO_VALUE
   #:MPI_ERR_INFO_NOKEY
   #:MPI_ERR_NAME
   #:MPI_ERR_NO_MEM
   #:MPI_ERR_NOT_SAME
   #:MPI_ERR_PORT
   #:MPI_ERR_QUOTA
   #:MPI_ERR_SERVICE
   #:MPI_ERR_SPAWN
   #:MPI_ERR_UNSUPPORTED_OPERATION
   #:MPI_ERR_WIN
   #:MPI_ERR_BASE
   #:MPI_ERR_LOCKTYPE
   #:MPI_ERR_KEYVAL
   #:MPI_ERR_RMA_CONFLICT
   #:MPI_ERR_RMA_SYNC
   #:MPI_ERR_SIZE
   #:MPI_ERR_DISP
   #:MPI_ERR_ASSERT
   #:MPI_ERR_LASTCODE
   #:MPICH_ERR_LAST_CLASS
   #:MPI_Datarep_conversion_function
   #:MPI_Datarep_extent_function
   #:MPI_CONVERSION_FN_NULL
   #:MPI_Send
   #:MPI_Recv
   #:MPI_Get_count
   #:MPI_Bsend
   #:MPI_Ssend
   #:MPI_Rsend
   #:MPI_Buffer_attach
   #:MPI_Buffer_detach
   #:MPI_Isend
   #:MPI_Ibsend
   #:MPI_Issend
   #:MPI_Irsend
   #:MPI_Irecv
   #:MPI_Wait
   #:MPI_Test
   #:MPI_Request_free
   #:MPI_Waitany
   #:MPI_Testany
   #:MPI_Waitall
   #:MPI_Testall
   #:MPI_Waitsome
   #:MPI_Testsome
   #:MPI_Iprobe
   #:MPI_Probe
   #:MPI_Cancel
   #:MPI_Test_cancelled
   #:MPI_Send_init
   #:MPI_Bsend_init
   #:MPI_Ssend_init
   #:MPI_Rsend_init
   #:MPI_Recv_init
   #:MPI_Start
   #:MPI_Startall
   #:MPI_Sendrecv
   #:MPI_Sendrecv_replace
   #:MPI_Type_contiguous
   #:MPI_Type_vector
   #:MPI_Type_hvector
   #:MPI_Type_indexed
   #:MPI_Type_hindexed
   #:MPI_Type_struct
   #:MPI_Address
   #:MPI_Type_extent
   #:MPI_Type_size
   #:MPI_Type_lb
   #:MPI_Type_ub
   #:MPI_Type_commit
   #:MPI_Type_free
   #:MPI_Get_elements
   #:MPI_Pack
   #:MPI_Unpack
   #:MPI_Pack_size
   #:MPI_Barrier
   #:MPI_Bcast
   #:MPI_Gather
   #:MPI_Gatherv
   #:MPI_Scatter
   #:MPI_Scatterv
   #:MPI_Allgather
   #:MPI_Allgatherv
   #:MPI_Alltoall
   #:MPI_Alltoallv
   #:MPI_Reduce
   #:MPI_Op_create
   #:MPI_Op_free
   #:MPI_Allreduce
   #:MPI_Reduce_scatter
   #:MPI_Scan
   #:MPI_Group_size
   #:MPI_Group_rank
   #:MPI_Group_translate_ranks
   #:MPI_Group_compare
   #:MPI_Comm_group
   #:MPI_Group_union
   #:MPI_Group_intersection
   #:MPI_Group_difference
   #:MPI_Group_incl
   #:MPI_Group_excl
   #:MPI_Group_range_incl
   #:MPI_Group_range_excl
   #:MPI_Group_gree
   #:MPI_Comm_size
   #:MPI_Comm_compare
   #:MPI_Comm_dup
   #:MPI_Comm_create
   #:MPI_Comm_split
   #:MPI_Comm_free
   #:MPI_Comm_test_inter
   #:MPI_Comm_remote_size
   #:MPI_Comm_remote_group
   #:MPI_Intercomm_create
   #:MPI_Intercomm_merge
   #:MPI_Keyval_create
   #:MPI_Keyval_free
   #:MPI_Attr_put
   #:MPI_Attr_get
   #:MPI_Attr_delete
   #:MPI_Topo_test
   #:MPI_Cart_create
   #:MPI_Dims_create
   #:MPI_Graph_create
   #:MPI_Graphdims_get
   #:MPI_Graph_get
   #:MPI_Cartdim_get
   #:MPI_Cart_get
   #:MPI_Cart_rank
   #:MPI_Cart_coords
   #:MPI_Graph_neighbors_count
   #:MPI_Graph_neighbors
   #:MPI_Cart_shift
   #:MPI_Cart_sub
   #:MPI_Cart_map
   #:MPI_Graph_map
   #:MPI_Get_processor_name
   #:MPI_Get_version
   #:MPI_Errhandler_create
   #:MPI_Errhandler_set
   #:MPI_Errhandler_get
   #:MPI_Errhandler_free
   #:MPI_Error_string
   #:MPI_Error_class
   #:MPI_Wtime
   #:MPI_Wtick
   #:MPI_Finalize
   #:MPI_Abort
   #:MPI_Pcontrol
   #:MPI_Close_port
   #:MPI_Comm_accept
   #:MPI_Comm_connect
   #:MPI_Comm_disconnect
   #:MPI_Comm_get_parent
   #:MPI_Comm_join
   #:MPI_Comm_spawn
   #:MPI_Comm_spawn_multiple
   #:MPI_Lookup_name
   #:MPI_Open_port
   #:MPI_Publish_name
   #:MPI_Unpublish_name
   #:MPI_Accumulate
   #:MPI_Get
   #:MPI_Put
   #:MPI_Win_complete
   #:MPI_Win_create
   #:MPI_Win_fence
   #:MPI_Win_free
   #:MPI_Win_get_group
   #:MPI_Win_lock
   #:MPI_Win_post
   #:MPI_Win_start
   #:MPI_Win_test
   #:MPI_Win_unlock
   #:MPI_Win_wait
   #:MPI_Alltoallw
   #:MPI_Exscan
   #:MPI_Add_error_class
   #:MPI_Add_error_code
   #:MPI_Add_error_string
   #:MPI_Comm_call_errhandler
   #:MPI_Comm_create_keyval
   #:MPI_Comm_delete_attr
   #:MPI_Comm_free_keyval
   #:MPI_Comm_get_attr
   #:MPI_Comm_get_name
   #:MPI_Comm_Set_attr
   #:MPI_Comm_set_name
   #:MPI_File_call_errhandler
   #:MPI_Grequest_complete
   #:MPI_Grequest_start
   #:MPI_Is_thread_main
   #:MPI_Query_thread
   #:MPI_Status_set_cancelled
   #:MPI_Status_set_elements
   #:MPI_Type_create_keyval
   #:MPI_Type_delete_attr
   #:MPI_Type_dup
   #:MPI_Type_free_keyval
   #:MPI_Type_get_attr
   #:MPI_Type_get_contents
   #:MPI_Type_get_envelope
   #:MPI_Type_get_name
   #:MPI_Type_set_attr
   #:MPI_Type_set_name
   #:MPI_Type_match_size
   #:MPI_Win_call_errhandler
   #:MPI_Win_create_keyval
   #:MPI_Win_delete_attr
   #:MPI_Win_free_keyval
   #:MPI_Win_get_attr
   #:MPI_Win_get_name
   #:MPI_Win_set_attr
   #:MPI_Win_set_name
   #:MPI_Alloc_mem
   #:MPI_Comm_create_errhandler
   #:MPI_Comm_get_errhandler
   #:MPI_Comm_set_errhandler
   #:MPI_File_create_errhandler
   #:MPI_File_get_errhandler
   #:MPI_File_set_errhandler
   #:MPI_Finalized
   #:MPI_Free_mem
   #:MPI_Get_address
   #:MPI_Info_create
   #:MPI_Info_delete
   #:MPI_Info_dup
   #:MPI_Info_free
   #:MPI_Info_get
   #:MPI_Info_get_nkeys
   #:MPI_Info_get_nthkey
   #:MPI_Info_get_valuelen
   #:MPI_Info_set
   #:MPI_Pack_external
   #:MPI_Pack_external_size
   #:MPI_Request_get_status
   #:MPI_Status_c2f
   #:MPI_Status_f2c
   #:MPI_Type_create_darray
   #:MPI_Type_create_hindexed
   #:MPI_Type_create_hvector
   #:MPI_Type_create_indexed_block
   #:MPI_Type_create_resized
   #:MPI_Type_create_struct
   #:MPI_Type_create_subarray
   #:MPI_Type_get_extent
   #:MPI_Type_get_true_extent
   #:MPI_Unpack_external
   #:MPI_Win_create_errhandler
   #:MPI_Win_get_errhandler
   #:MPI_Win_set_errhandler
   #:MPI_Type_create_f90_integer
   #:MPI_Type_create_f90_real
   #:MPI_Type_create_f90_complex
   #:PMPI_Send
   #:PMPI_Recv
   #:PMPI_Get_count
   #:PMPI_Bsend
   #:PMPI_Ssend
   #:PMPI_Rsend
   #:PMPI_Buffer_attach
   #:PMPI_Buffer_detach
   #:PMPI_Isend
   #:PMPI_Ibsend
   #:PMPI_Issend
   #:PMPI_Irsend
   #:PMPI_Irecv
   #:PMPI_Wait
   #:PMPI_Test
   #:PMPI_Request_free
   #:PMPI_Waitany
   #:PMPI_Testany
   #:PMPI_Waitall
   #:PMPI_Testall
   #:PMPI_Waitsome
   #:PMPI_Testsome
   #:PMPI_Iprobe
   #:PMPI_Probe
   #:PMPI_Cancel
   #:PMPI_Test_cancelled
   #:PMPI_Send_init
   #:PMPI_Bsend_init
   #:PMPI_Ssend_init
   #:PMPI_Rsend_init
   #:PMPI_Recv_init
   #:PMPI_Start
   #:PMPI_Startall
   #:PMPI_Sendrecv
   #:PMPI_Sendrecv_replace
   #:PMPI_Type_contiguous
   #:PMPI_Type_vector
   #:PMPI_Type_hvector
   #:PMPI_Type_indexed
   #:PMPI_Type_hindexed
   #:PMPI_Type_struct
   #:PMPI_Address
   #:PMPI_Type_extent
   #:PMPI_Type_size
   #:PMPI_Type_lb
   #:PMPI_Type_ub
   #:PMPI_Type_commit
   #:PMPI_Type_free
   #:PMPI_Get_elements
   #:PMPI_Pack
   #:PMPI_Unpack
   #:PMPI_Pack_size
   #:PMPI_Barrier
   #:PMPI_Bcast
   #:PMPI_Gather
   #:PMPI_Gatherv
   #:PMPI_Scatter
   #:PMPI_Scatterv
   #:PMPI_Allgather
   #:PMPI_Allgatherv
   #:PMPI_Alltoall
   #:PMPI_Alltoallv
   #:PMPI_Reduce
   #:PMPI_Op_create
   #:PMPI_Op_free
   #:PMPI_Allreduce
   #:PMPI_Reduce_scatter
   #:PMPI_Scan
   #:PMPI_Group_size
   #:PMPI_Group_rank
   #:PMPI_Group_translate_ranks
   #:PMPI_Group_compare
   #:PMPI_Comm_group
   #:PMPI_Group_union
   #:PMPI_Group_intersection
   #:PMPI_Group_difference
   #:PMPI_Group_incl
   #:PMPI_Group_excl
   #:PMPI_Group_range_incl
   #:PMPI_Group_range_excl
   #:PMPI_Group_gree
   #:PMPI_Comm_size
   #:PMPI_Comm_rank
   #:PMPI_Comm_compare
   #:PMPI_Comm_dup
   #:PMPI_Comm_create
   #:PMPI_Comm_split
   #:PMPI_Comm_free
   #:PMPI_Comm_test_inter
   #:PMPI_Comm_remote_size
   #:PMPI_Comm_remote_group
   #:PMPI_Intercomm_create
   #:PMPI_Intercomm_merge
   #:PMPI_Keyval_create
   #:PMPI_Keyval_free
   #:PMPI_Attr_put
   #:PMPI_Attr_get
   #:PMPI_Attr_delete
   #:PMPI_Topo_test
   #:PMPI_Cart_create
   #:PMPI_Dims_create
   #:PMPI_Graph_create
   #:PMPI_Graphdims_get
   #:PMPI_Graph_get
   #:PMPI_Cartdim_get
   #:PMPI_Cart_get
   #:PMPI_Cart_rank
   #:PMPI_Cart_coords
   #:PMPI_Graph_neighbors_count
   #:PMPI_Graph_neighbors
   #:PMPI_Cart_shift
   #:PMPI_Cart_sub
   #:PMPI_Cart_map
   #:PMPI_Graph_map
   #:PMPI_Get_processor_name
   #:PMPI_Get_version
   #:PMPI_Errhandler_create
   #:PMPI_Errhandler_set
   #:PMPI_Errhandler_get
   #:PMPI_Errhandler_free
   #:PMPI_Error_string
   #:PMPI_Error_class
   #:PMPI_Wtime
   #:PMPI_Wtick
   #:PMPI_Init
   #:PMPI_Finalize
   #:PMPI_Initialized
   #:PMPI_Abort
   #:PMPI_Pcontrol
   #:PMPI_Close_port
   #:PMPI_Comm_accept
   #:PMPI_Comm_connect
   #:PMPI_Comm_disconnect
   #:PMPI_Comm_get_parent
   #:PMPI_Comm_join
   #:PMPI_Comm_spawn
   #:PMPI_Comm_spawn_multiple
   #:PMPI_Lookup_name
   #:PMPI_Open_port
   #:PMPI_Publish_name
   #:PMPI_Unpublish_name
   #:PMPI_Accumulate
   #:PMPI_Get
   #:PMPI_Put
   #:PMPI_Win_complete
   #:PMPI_Win_create
   #:PMPI_Win_fence
   #:PMPI_Win_free
   #:PMPI_Win_get_group
   #:PMPI_Win_lock
   #:PMPI_Win_post
   #:PMPI_Win_start
   #:PMPI_Win_test
   #:PMPI_Win_unlock
   #:PMPI_Win_wait
   #:PMPI_Alltoallw
   #:PMPI_Exscan
   #:PMPI_Add_error_class
   #:PMPI_Add_error_code
   #:PMPI_Add_error_string
   #:PMPI_Comm_call_errhandler
   #:PMPI_Comm_create_keyval
   #:PMPI_Comm_delete_attr
   #:PMPI_Comm_free_keyval
   #:PMPI_Comm_get_attr
   #:PMPI_Comm_get_name
   #:PMPI_Comm_Set_attr
   #:PMPI_Comm_set_name
   #:PMPI_File_call_errhandler
   #:PMPI_Grequest_complete
   #:PMPI_Grequest_start
   #:PMPI_Init_thread
   #:PMPI_Is_thread_main
   #:PMPI_Query_thread
   #:PMPI_Status_set_cancelled
   #:PMPI_Status_set_elements
   #:PMPI_Type_create_keyval
   #:PMPI_Type_delete_attr
   #:PMPI_Type_dup
   #:PMPI_Type_free_keyval
   #:PMPI_Type_get_attr
   #:PMPI_Type_get_contents
   #:PMPI_Type_get_envelope
   #:PMPI_Type_get_name
   #:PMPI_Type_set_attr
   #:PMPI_Type_set_name
   #:PMPI_Type_match_size
   #:PMPI_Win_call_errhandler
   #:PMPI_Win_create_keyval
   #:PMPI_Win_delete_attr
   #:PMPI_Win_free_keyval
   #:PMPI_Win_get_attr
   #:PMPI_Win_get_name
   #:PMPI_Win_set_attr
   #:PMPI_Win_set_name
   #:PMPI_Alloc_mem
   #:PMPI_Comm_create_errhandler
   #:PMPI_Comm_get_errhandler
   #:PMPI_Comm_set_errhandler
   #:PMPI_File_create_errhandler
   #:PMPI_File_get_errhandler
   #:PMPI_File_set_errhandler
   #:PMPI_Finalized
   #:PMPI_Free_mem
   #:PMPI_Get_address
   #:PMPI_Info_create
   #:PMPI_Info_delete
   #:PMPI_Info_dup
   #:PMPI_Info_free
   #:PMPI_Info_get
   #:PMPI_Info_get_nkeys
   #:PMPI_Info_get_nthkey
   #:PMPI_Info_get_valuelen
   #:PMPI_Info_set
   #:PMPI_Pack_external
   #:PMPI_Pack_external_size
   #:PMPI_Request_get_status
   #:PMPI_Status_c2f
   #:PMPI_Status_f2c
   #:PMPI_Type_create_darray
   #:PMPI_Type_create_hindexed
   #:PMPI_Type_create_hvector
   #:PMPI_Type_create_indexed_block
   #:PMPI_Type_create_resized
   #:PMPI_Type_create_struct
   #:PMPI_Type_create_subarray
   #:PMPI_Type_get_extent
   #:PMPI_Type_get_true_extent
   #:PMPI_Unpack_external
   #:PMPI_Win_create_errhandler
   #:PMPI_Win_get_errhandler
   #:PMPI_Win_set_errhandler
   #:PMPI_Type_create_f90_integer
   #:PMPI_Type_create_f90_real
   #:PMPI_Type_create_f90_complex
   #:MPIIMPL_ADVERTISES_FEATURES
   #:MPIIMPL_HAVE_MPI_INFO
   #:MPIIMPL_HAVE_MPI_COMBINER_DARRAY
   #:MPIIMPL_HAVE_MPI_TYPE_CREATE_DARRAY
   #:MPIIMPL_HAVE_MPI_COMBINER_SUBARRAY
   #:MPIIMPL_HAVE_MPI_TYPE_CREATE_DARRAY
   #:MPIIMPL_HAVE_MPI_COMBINER_DUP
   #:MPIIMPL_HAVE_MPI_GREQUEST
   #:MPIIMPL_HAVE_STATUS_SET_BYTES
   #:MPIIMPL_HAVE_STATUS_SET_INFO
   #:MPIX_Grequest_poll_function
   #:MPIX_Grequest_wait_function
   #:MPIX_Grequest_class
   #:MPIX_Grequest_class_create
   #:MPIX_Grequest_class_allocate
   #:MPIX_Grequest_start
   #:PMPIX_Grequest_class_create
   #:PMPIX_Grequest_class_allocate
   #:PMPIX_Grequest_start

   ;; from mpio-h
   #:ROMIO_VERSION
   #:MPIO_Request
   #:MPIO_Wait
   #:MPIO_Test
   #:PMPIO_Wait
   #:PMPIO_Test
   #:MPI_MODE_RDONLY
   #:MPI_MODE_RDWR
   #:MPI_MODE_WRONLY
   #:MPI_MODE_CREATE
   #:MPI_MODE_EXCL
   #:MPI_MODE_DELETE_ON_CLOSE
   #:MPI_MODE_UNIQUE_OPEN
   #:MPI_MODE_APPEND
   #:MPI_MODE_SEQUENTIAL
   #:MPI_DISPLACEMENT_CURRENT
   #:MPIO_REQUEST_NULL
   #:MPI_SEEK_SET
   #:MPI_SEEK_CUR
   #:MPI_SEEK_END
   #:MPI_MAX_DATAREP_STRING
   #:MPI_File_open
   #:MPI_File_close
   #:MPI_File_delete
   #:MPI_File_set_size
   #:MPI_File_preallocate
   #:MPI_File_get_size
   #:MPI_File_get_group
   #:MPI_File_get_amode
   #:MPI_File_set_info
   #:MPI_File_get_info
   #:MPI_File_set_view
   #:MPI_File_get_view
   #:MPI_File_read_at
   #:MPI_File_read_at_all
   #:MPI_File_write_at
   #:MPI_File_write_at_all
   #:MPI_File_iread_at
   #:MPI_File_iwrite_at
   #:MPI_File_read
   #:MPI_File_read_all
   #:MPI_File_write
   #:MPI_File_write_all
   #:MPI_File_iread
   #:MPI_File_iwrite
   #:MPI_File_seek
   #:MPI_File_get_position
   #:MPI_File_get_byte_offset
   #:MPI_File_read_shared
   #:MPI_File_write_shared
   #:MPI_File_iread_shared
   #:MPI_File_iwrite_shared
   #:MPI_File_read_ordered
   #:MPI_File_write_ordered
   #:MPI_File_seek_shared
   #:MPI_File_get_position_shared
   #:MPI_File_read_at_all_begin
   #:MPI_File_read_at_all_end
   #:MPI_File_write_at_all_begin
   #:MPI_File_write_at_all_end
   #:MPI_File_read_all_begin
   #:MPI_File_read_all_end
   #:MPI_File_write_all_begin
   #:MPI_File_write_all_end
   #:MPI_File_read_ordered_begin
   #:MPI_File_read_ordered_end
   #:MPI_File_write_ordered_begin
   #:MPI_File_write_ordered_end
   #:MPI_File_get_type_extent
   #:MPI_Register_datarep
   #:MPI_File_set_atomicity
   #:MPI_File_get_atomicity
   #:MPI_File_sync
   #:MPI_File_f2c
   #:MPI_File_c2f
   #:PMPI_File_open
   #:PMPI_File_close
   #:PMPI_File_delete
   #:PMPI_File_set_size
   #:PMPI_File_preallocate
   #:PMPI_File_get_size
   #:PMPI_File_get_group
   #:PMPI_File_get_amode
   #:PMPI_File_set_info
   #:PMPI_File_get_info
   #:PMPI_File_set_view
   #:PMPI_File_get_view
   #:PMPI_File_read_at
   #:PMPI_File_read_at_all
   #:PMPI_File_write_at
   #:PMPI_File_write_at_all
   #:PMPI_File_iread_at
   #:PMPI_File_iwrite_at
   #:PMPI_File_read
   #:PMPI_File_read_all
   #:PMPI_File_write
   #:PMPI_File_write_all
   #:PMPI_File_iread
   #:PMPI_File_iwrite
   #:PMPI_File_seek
   #:PMPI_File_get_position
   #:PMPI_File_get_byte_offset
   #:PMPI_File_read_shared
   #:PMPI_File_write_shared
   #:PMPI_File_iread_shared
   #:PMPI_File_iwrite_shared
   #:PMPI_File_read_ordered
   #:PMPI_File_write_ordered
   #:PMPI_File_seek_shared
   #:PMPI_File_get_position_shared
   #:PMPI_File_read_at_all_begin
   #:PMPI_File_read_at_all_end
   #:PMPI_File_write_at_all_begin
   #:PMPI_File_write_at_all_end
   #:PMPI_File_read_all_begin
   #:PMPI_File_read_all_end
   #:PMPI_File_write_all_begin
   #:PMPI_File_write_all_end
   #:PMPI_File_read_ordered_begin
   #:PMPI_File_read_ordered_end
   #:PMPI_File_write_ordered_begin
   #:PMPI_File_write_ordered_end
   #:PMPI_File_get_type_extent
   #:PMPI_Register_datarep
   #:PMPI_File_set_atomicity
   #:PMPI_File_get_atomicity
   #:PMPI_File_sync
   #:PMPI_File_f2c
   #:PMPI_File_c2f
   ))
